package dev.agenticcommerce.gateway.agentization.model;

public enum AgentToolName {
    INSPECT_SPEC,
    INSPECT_SCHEMA,
    PROPOSE_MAPPING,
    VALIDATE_MAPPING,
    RUN_CONTRACT_TEST,
    INSPECT_TEST_FAILURE,
    REVISE_MAPPING,
    INSPECT_POLICY,
    EXTRACT_POLICY_RULES,
    INSPECT_CATALOG_SAMPLE,
    REQUEST_MERCHANT_CLARIFICATION,
    REQUEST_MERCHANT_APPROVAL,
    PUBLISH_MANIFEST_CANDIDATE
}
